Update insert_into_table
changed insertion logic to validate each value at a time instead of validation all values at once

diff --git a/insert_into_table b/insert_into_table
--- a/insert_into_table
+++ b/insert_into_table
@@ -8,24 +8,21 @@ read -p "Enter the table you want to insert into: " tname
 	else
 		
 		table=${tname,,}
-		if [ -e $table ] # 2 if
+		if [[ -f $table && -f ".meta$table" ]] # 2 if
 		then
-			
-			# check if .meta file exists
-			if [[ ! -f ".meta$table" ]] # 3 if
-			then 
-				echo "Error: metadata file .meta$table not found!"
-				break
-			fi # 3 if
 			
 			# inserting metadata file lines into an array called columns
 			mapfile -t columns < ".meta$table"
 			
 			
 			# looping to take user's input for every column
-			col_num=$(wc -l .meta$table | cut -d" " -f1)
+			col_num=$(head -n -1 .meta$table | wc -l | cut -d" " -f1)
 			declare -a values
 			
+			line=""
+			valid_row=1
+			
+			# looping over each of one of the columns to get input value and validate it
 			for ((i=0;i<$col_num;i++))
 			do 
 				col_name=$(echo ${columns[$i]} | cut -d: -f1)
@@ -33,62 +30,52 @@ read -p "Enter the table you want to insert into: " tname
 				
 				read -p "Enter value for $col_name($col_type): " values[$i]
 				
-				
-			done
 			
-			line=""
-			valid_row=1
 			# validation primary key insertion
+			if [[ $i -eq 0 && $valid_row -eq 1 ]]; then
 			
-			col_name=$(echo ${columns[0]} | cut -d: -f1)
-			col_type=$(echo ${columns[0]} | cut -d: -f2)
-			validpk=$(grep -E "^${values[0]}" "$table" | cut -d: -f1)
-			
-			# check if there's a row starts with the first value entered (in pk col)
+			validpk=$(grep -E "^${values[$i]}" "$table" | cut -d: -f1)  # check if there's a row starts with the first value entered (in pk col)
 			
 			if [[ -z $validpk ]] # 4 if
 			then 
-				# if we found nothing >> continue chacking the column type
+				# if we found match >> continue chacking the column type
 				if [[ $col_type = "num" ]] # 5 if
 				then
-					if ! [[ ${values[0]} =~ ^[0-9]+$ ]] # 6 if
+					if ! [[ ${values[$i]} =~ ^[0-9]+$ ]] # 6 if
 					then
 						echo "Error: column $col_name type is $col_type! You must enter a unique numeric value"
 						valid_row=0
 					
 					else
-						line+=${values[0]}
+						line+=${values[$i]}
 
 					fi # 6 if
 				elif [[ $col_type = "str" ]] # 5 if
 				then
-					if [[ -z ${values[0]} ]] #7  if
+					if [[ -z ${values[$i]} ]] #7  if
 					then
 						echo  "Error: You should enter a non-empty unique value for column $col_name(PK)"
 						valid_row=0
 						
 					else
-						line+=${values[0]}
+						line+=${values[$i]}
 					fi # 7 if
 						
 				fi #5 if
-			elif [[ -z ${values[0]} ]]
+			elif [[ -z ${values[$i]} ]]
 					then
 						echo "Error: You should enter a non-empty unique value for column $col_name(PK)"
 						valid_row=0
 			# if we found duplicate
 			else
-				echo "${values[0]} already exists in $col_name, voilating primary key constraint!"
+				echo "${values[$i]} already exists in $col_name, voilating primary key constraint!"
 				valid_row=0
 				 
 			fi # 4 if
-			
-			# looping over each of one of the columns except the PK
-			for ((i=1;i<$col_num;i++))
-			do 
-				col_name=$(echo ${columns[$i]} | cut -d: -f1)
-				col_type=$(echo ${columns[$i]}  | cut -d: -f2)
+		fi
 				
+######################## Validating the rest of the columns #################
+		if [[ $i -gt 0 && $valid_row -eq 1 ]]; then
 				
 				if [[ $col_type = "num" ]] # 8 if
 				then
@@ -117,15 +104,23 @@ read -p "Enter the table you want to insert into: " tname
 						
 					fi # 10 if
 				fi # 9 if
+				fi
+			
+			if [[ $valid_row -eq 0 ]]; then
+			    line=""
+			    echo "Row insertion aborted due to invalid input."
+			    break # Exit the loop if any column is invalid
+			  fi
 					
 			done
 			
-			if [[ $valid_row = 1 ]]
+			
+			if [[ $valid_row -eq 1 ]]
 			then
 				echo $line >> $table
 				echo "$line is inserted into the table" 
 			fi
-			line=""
+
 			
 		else	
 			echo "$table does not exist"
