Update update_table
- fixed updating where the search column is not where the update column
- updated the logic of the menu to include only one option for the update (update by searching value)
- added exit option
- added check primary key constraint

diff --git a/update_table b/update_table
--- a/update_table
+++ b/update_table
@@ -7,121 +7,25 @@ ls ~/DBMS/$dbName/
 
 
 
-##### 2- entre table and check if it's in DBMS
-read -p "Enter the name of the table you chosed to update: " tName
-
-
-#### 3- created variables to hold the baths of table / metadata
-meta_path=".meta$tName"
-table_path=~/DBMS/$dbName/$tName
-#echo $table_path
-#echo $meta_path
-
-### 4- checked if the path exist 
-if [ -e "$table_path" ]; then
-    PS3="Please choose an option from the menu: "
-    
+PS3="Please choose an option [1-2]: "   
 
 ### 5- LIST TO MAKE HIM CHOSE THE METHOD OF UPDATING (pk/value)
-    select option in "Update using PK" "Update using specific value" ; do
+    select option in "Update" "Exit" ; do
         case $option in
-            "Update using PK")
-               
-
-### 6-READING 3 VARIABLES TO USE 
-
-                read -p "Enter the primary key (ID) of the row to update: " pk                  ### (1)Identifies the row to be updated.
-                     		
-### 7-Find the row number by primary key
-		row_number=$(awk -v pk="$pk" -F: '$1 == pk {print NR}' "$table_path")
-
-##so awk will look line by line for $pk  in an insider variable called pk(with field sepretor : )and {{'$1 == pk {print NR}'}} ------> This will  check if field 1 == pk ($pk ) if true print NR --> num of record		                
-             
-		
-### 8-check if row exists (The -z operator returns true if the variable is empty.)
-
-		if [[ -z $row_number ]]; then
-    		echo "Row with primary key '$pk' not found."
-   		 break
-		fi	                
-                
-
-		read -p "Enter the column name to update: " column_name                         ###(2)The column to update.
-		
-### 9-Find the column index for the specified column name
-
-col_index=$(awk -v col="$column_name" -F: '
-NR == 1 {
-  for (i = 1; i <= NF; i++) {
-    if ($i == col) {
-      print i
-      exit
-    }
-  }
-}
-
-' "$table_path")
-
-echo $col_index		
-		
-### 10-Check if the column exists
-
-		if [[ -z $col_index ]]; then
-    		echo "Column '$column_name' not found."
-   		break
-		fi
-
-		
-		
-		read -p "Enter the new value: " new_value                                       ### (3)The new value to set in the column.
-		
-		
-
-#data-validation
-###11- create variable col_type to grep data type based on colum_name 
-col_type=$(grep -E "^$column_name:" "$meta_path" | cut -d: -f2)
-
-echo "Column type for $column_name: $col_type"     # for checking test purpose
-
-### 12- two ifs to check it's not updating with wrong data type
-if [[ "$col_type" = "str" ]]; then
-    if ! [[ "$new_value" =~ ^[a-zA-Z]+$ ]]; then
-        echo "Error: Value must be a string."
-	break
-    fi
-elif [[ "$col_type" = "num" ]]; then
-    if ! [[ "$new_value" =~ ^[0-9]+$ ]]; then
-        echo "Error: Value must be a numeric."
-	break
-    fi
-else
-    echo "Unknown column type: $col_type"
-	break 
-fi
-
-echo "Validation passed. Proceeding with update..."
+            "Update")
+               valid=1
+	##### 2- entre table and check if it's in DBMS
+	read -p "Enter the name of the table to update: " tName
 
 
+	#### 3- created variables to hold the baths of table / metadata
+	
+	meta_path=".meta$tName"
+	table_path=~/DBMS/$dbName/$tName
+	
 
-### 13-Update the row Passes the row number/ Passes the column index./Passes the new value.   
- 
-		awk -v row="$row_number" -v col="$col_index" -v new_val="$new_value" -F':' -v OFS=':' '
-		NR == row { $col = new_val } { print $0 }
-		' "$table_path" > tmp && mv tmp "$table_path"
-
-		echo "Row updated successfully."
-                break
-          	;;          
-
-############################################################################################################################################
-
-
-### 14- the second option 
-            "Update using specific value")
-            
-            
-            
-### 15-READING 3 VARIABLES TO USE ###
+	### 4- checked if the path exist 
+	if [ -f "$table_path" ]; then
 
  ######### (1) Identifies the column to search for the specific value ########
         read -p "Enter the column name to search by: " search_col
@@ -139,10 +43,11 @@ echo "Validation passed. Proceeding with update..."
         ' "$table_path")
     
 ### 17 - Check if the column exists
-        if [[ -z $search_col_index ]]; then
+        if  [[ -z $search_col_index ]]; then
             echo "Column '$search_col' not found."
-            break
-        fi
+            valid=0
+            else
+        
 
  ######### (2) Enter the value to search for ########################
         read -p "Enter the value to search for: " search_value
@@ -155,16 +60,16 @@ echo "Validation passed. Proceeding with update..."
 ### 19- Validate if a matching row exists
         if [[ -z $row_number ]]; then
             echo "No rows found where '$search_col' equals '$search_value'."
-            break
-        fi
+            valid=0
+        else
 
 #### the update a specific column in the matching row ###
 
  ################# (3) Enter the column name to update ####################
-        ##read -p "Enter the column name to update: " update_col
+        read -p "Enter the column name to update: " update_col
 
 ### 20- Find the column index for the column to update
-        update_col_index=$(awk -v col="$search_col" -F: '
+        update_col_index=$(awk -v col="$update_col" -F: '
         NR == 1 {
             for (i = 1; i <= NF; i++) {
                 if ($i == col) {
@@ -178,48 +83,90 @@ echo "Validation passed. Proceeding with update..."
 ### 21- Check if the column exists
         if [[ -z $update_col_index ]]; then
             echo "Column '$update_col' not found."
-            break
-        fi
+            valid=0
+        else
 
 ####################### (4) Enter the new value ################################
         read -p "Enter the new value: " new_value
 
 ############################# Data Validation ###
         col_type=$(grep -E "^$search_col:" "$meta_path" | cut -d: -f2)
+        pk_flag=$(grep -E "^$search_col:" "$meta_path" | cut -d: -f3)
+	valid=1
+########################### Validating primary key #########################
+	if [[ $pk_flag == PK ]]; then # check pk constraint
+		validpk=$(grep -E "^$new_value" "$table_path" | cut -d: -f1)  # check if there's a row starts with the first value entered (in pk col)
+	
+	  if [[ -z $validpk || -z $new_value ]] ; then 	
+		
+		if [[ "$col_type" = "str" ]]; then
+		    if ! [[ "$new_value" =~ ^[a-zA-Z0-9]+$ ]]; then
+		     
+			echo  "Error: You should enter a non-empty unique value for column $update_col(PK)"
+			valid=0
+						
+			fi
+		elif [[ "$col_type" = "num" ]]; then
+		    if ! [[ "$new_value" =~ ^[0-9]+$ ]]; then
+		         echo "Error: column $update_col type is $col_type! You must enter a unique numeric value"
+			valid=0
+		    fi
+		fi
+	
+	else 
+		echo "$new_value already exists in $update_col, voilating primary key constraint!"
+		valid=0
 
-        if [[ "$col_type" = "str" ]]; then
-            if ! [[ "$new_value" =~ ^[a-zA-Z]+$ ]]; then
-                echo "Error: Value must be a string."
-                break
-            fi
-        elif [[ "$col_type" = "num" ]]; then
-            if ! [[ "$new_value" =~ ^[0-9]+$ ]]; then
-                echo "Error: Value must be numeric."
-                break
-            fi
-        else
-            echo "Unknown column type: $col_type"
-            break
-        fi
+	fi
+	
+#######################validating other columns#############################
+	else
+	if [[ "$col_type" = "str" ]]; then
+		if [[ -z "$new_value" ]]; then
+		     
+			echo  "Error: You should enter a non-empty string value for column $update_col"
+			valid=0
+						
+			fi
+		elif [[ "$col_type" = "num" ]]; then
+		    if ! [[ "$new_value" =~ ^[0-9]+$ ]]; then
+		         echo "Error: column $update_col type is number! You must enter a numeric value"
+			valid=0
+		    fi
+		fi
+fi
+fi
+fi
+fi
+##################### Perform the update #################################
 
-        echo "Validation passed. Proceeding with update..."
-
-##################### Perform the update ###
+if [[ $valid -eq 1 ]];then 
+	echo "Validation passed. Proceeding with update..."
         awk -v row="$row_number" -v col="$update_col_index" -v new_val="$new_value" -F':' -v OFS=':' '
         NR == row { $col = new_val } { print $0 }
         ' "$table_path" > tmp && mv tmp "$table_path"
 
         echo "Row updated successfully."
-        break
-      		  ;;
+      	fi	  
+          	  
+      else
+    echo "Table $tName does not exist."
+    
+fi        
+;;
+############################################################################################################################################
+
+
+### 14- the exit option 
+            "Exit")
+            echo "Exiting update menu.." 
+            break
+            ;;
 
   	
             *)
                 echo "Invalid option. Please try again."
                 ;;
         esac
-        break
     done
-else
-    echo "Table $tName does not exist."
-fi
+
